name: hestimate
version: 0.1.0.0
license: BSD3
author: "Da Team"
copyright: "MIT"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant-server
  - wai
  - wai-cors
  - warp
  - postgresql-simple
  - resource-pool
  - bytestring
  - mtl

library:
  source-dirs: src
  dependencies:
    - aeson

executables:
  hestimate-exe:
    main: app/Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hestimate

tests:
  hestimate-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - aeson
      - bytestring
      - hestimate
      - hspec
      - hspec-wai
      - hspec-wai-json
      - http-types
      - utf8-string
      - wai-extra
      - QuickCheck
