on: [push]
name: build
jobs:
  build-and-test:
    name: hestimate build & test
    runs-on: ubuntu-latest
    env:
      GHC_VERSION: '8.8.3'
      STACK_VERSION: 'latest'

    steps:
      - uses: actions/checkout@v2

      - name: Setup haskell compiler
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ env.GHC_VERSION }}
          enable-stack: true
          stack-version: ${{ env.STACK_VERSION }}

      - name: Cache dependencies (Unix)
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build
        run: stack build --test --no-run-tests --bench --no-run-benchmarks

      - name: Test
        run: stack test
